name: Train Pipeline Schedule

on:
  workflow_dispatch: # allows fo manual triggering of the workflow.
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at 00:00 UTC

permissions:
  contents: write # Allows the workflow to push changes to the repository

jobs:
  run-train-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Feature Data Pipeline
        run: python pipelines/train_pipeline.py

      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated update"
          git push origin master 
